  - hosts: webservers
    vars:
      root_dir: /var/tmp/www
      nginx_port: 80

    tasks:
      - name: install packages (nginx, cowsay)
        ansible.builtin.apt:
          name:
            - nginx
            - cowsay
          state: latest
        become: yes

      - name: register cowsay result
        ansible.builtin.shell: cowsay "This is {{ server_name }}" 
        register: cowsay_result

      - name: create root dir
        ansible.builtin.file:
          path: "{{ root_dir }}"
          state: directory
        become: yes
    
      - name: copy html file
        ansible.builtin.template:
          src: files/index.html.j2
          dest: "{{ root_dir }}/index.html"
        become: yes

      - name: update nginx config
        ansible.builtin.template:
          src: files/nginx.conf.j2
          dest: /etc/nginx/nginx.conf
        notify:
          - restart nginx
        become: yes

    handlers:
      - name: restart nginx
        ansible.builtin.service:
          name: nginx
          state: reloaded
        become: yes
      

