 - hosts: webservers

   tasks:
     - name: debug message
       ansible.builtin.debug:
         msg: mainPlaybook
    
 - name: import git playbook
   ansible.builtin.import_playbook: gitDown.yml

 - name: import users playbook
   ansible.builtin.import_playbook: ./users/usersDown.yml

 - name: import server playbook
   ansible.builtin.import_playbook: ./nginx-server/downServer.yml 
