- hosts: webservers
  gather_facts: no
  vars:
    users:
      - jaime
      - sansa
      - robert
  tasks:
    - name: create users
      ansible.builtin.user:
        name: {{ item }}
        state: present
      become: yes 
      loop:
        - users

